using UrbanGrid.Core.Enums;

namespace UrbanGrid.Application.DTOs.Auth;

public class CreateStaffRequest
{
    public string Name { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public UserRole Role { get; set; }
    public string? Phone { get; set; }
    public string? EmployeeId { get; set; }
    public string? Department { get; set; }
    // ✅ No password — auto-generated by backend
}
